// Global broker & exchange API roster, grouped by the markets each serves.
// Same row shape as the Indian providers (stored in india_api_providers with a
// `markets` tag). Forex/CFD and crypto venues are global; equity brokers are
// tagged to their home market(s). Users only see brokers for the markets they
// selected.

import type { IndiaProviderDef } from './india/providers'

export const GLOBAL_BROKERS: IndiaProviderDef[] = [
  // ---- Forex & CFDs (global) ----
  {
    key: 'mt5_bridge',
    name: 'MetaTrader 5 Bridge',
    vendor: 'Any MT5 broker (IC Markets, Pepperstone, Exness, XM…)',
    docsUrl: 'https://www.mql5.com/en/docs/integration',
    baseUrl: 'mt5://terminal-bridge',
    authType: 'mt_account',
    authNote: 'Connects to any MT5 broker account: account number + password + broker server name. The bridge terminal handles quotes and execution.',
    exchanges: 'OTC — broker dependent',
    capabilities: 'quotes,historical,orders,portfolio,margins,hedging',
    rateLimitNote: 'Terminal-bound; no REST rate limits.',
    pricingNote: 'Free — trade costs are broker spreads/commissions.',
    markets: 'forex,metals,indices,energies,crypto',
  },
  {
    key: 'mt4_bridge',
    name: 'MetaTrader 4 Bridge',
    vendor: 'Any MT4 broker',
    docsUrl: 'https://docs.mql4.com/',
    baseUrl: 'mt4://terminal-bridge',
    authType: 'mt_account',
    authNote: 'Legacy MT4 accounts: account number + password + server name via the bridge terminal.',
    exchanges: 'OTC — broker dependent',
    capabilities: 'quotes,historical,orders,portfolio,margins,hedging',
    rateLimitNote: 'Terminal-bound.',
    pricingNote: 'Free — broker costs apply.',
    markets: 'forex,metals,indices,energies',
  },
  {
    key: 'oanda',
    name: 'OANDA v20 REST API',
    vendor: 'OANDA',
    docsUrl: 'https://developer.oanda.com/rest-live-v20/introduction/',
    baseUrl: 'https://api-fxtrade.oanda.com/v3',
    authType: 'static_token',
    authNote: 'Personal access token from the OANDA account portal, passed as a Bearer token. Practice environment at api-fxpractice.oanda.com.',
    exchanges: 'OTC',
    capabilities: 'quotes,historical,streaming,orders,portfolio,margins',
    rateLimitNote: '120 req/s REST; streaming endpoints for prices.',
    pricingNote: 'Free with an OANDA account.',
    markets: 'forex,metals,indices,energies',
  },
  {
    key: 'ig_markets',
    name: 'IG Trading API',
    vendor: 'IG Group',
    docsUrl: 'https://labs.ig.com/rest-trading-api-reference',
    baseUrl: 'https://api.ig.com/gateway/deal',
    authType: 'api_key_secret_daily_token',
    authNote: 'API key + account identifier + password; login returns CST and security tokens used on every request.',
    exchanges: 'OTC / LSE-referenced CFDs',
    capabilities: 'quotes,historical,streaming,orders,portfolio,margins',
    rateLimitNote: '30 non-trading req/min, 100 trading req/min (per app).',
    pricingNote: 'Free with an IG account.',
    markets: 'forex,indices,metals,energies,europe_stocks',
  },
  {
    key: 'saxo',
    name: 'Saxo OpenAPI',
    vendor: 'Saxo Bank',
    docsUrl: 'https://www.developer.saxo/openapi/learn',
    baseUrl: 'https://gateway.saxobank.com/openapi',
    authType: 'oauth2',
    authNote: 'OAuth2 app from the Saxo developer portal; access tokens are refreshed via the standard flow.',
    exchanges: 'Global multi-asset',
    capabilities: 'quotes,historical,streaming,orders,portfolio,margins',
    rateLimitNote: 'Per-app throttle policies by endpoint group.',
    pricingNote: 'Free with a Saxo account.',
    markets: 'forex,indices,europe_stocks,us_stocks',
  },
  {
    key: 'interactive_brokers',
    name: 'IBKR Web API',
    vendor: 'Interactive Brokers',
    docsUrl: 'https://www.interactivebrokers.com/campus/ibkr-api-page/web-api/',
    baseUrl: 'https://api.ibkr.com/v1/api',
    authType: 'oauth2',
    authNote: 'OAuth (or the Client Portal Gateway) authenticates the IBKR session. One account covers 150+ markets worldwide.',
    exchanges: 'NYSE,NASDAQ,LSE,XETRA,TSE,HKEX,ASX + forex',
    capabilities: 'quotes,historical,streaming,orders,portfolio,margins',
    rateLimitNote: '~10 req/s general; endpoint-specific throttles.',
    pricingNote: 'Free API; market-data subscriptions per exchange.',
    markets: 'us_stocks,europe_stocks,asia_stocks,forex,indices',
  },
  {
    key: 'ctrader',
    name: 'cTrader Open API',
    vendor: 'Spotware (FxPro, IC Markets cTrader, Pepperstone…)',
    docsUrl: 'https://help.ctrader.com/open-api/',
    baseUrl: 'https://openapi.ctrader.com',
    authType: 'oauth2',
    authNote: 'OAuth2 app from the cTrader developer portal; works with any broker running cTrader.',
    exchanges: 'OTC — broker dependent',
    capabilities: 'quotes,historical,streaming,orders,portfolio,margins',
    rateLimitNote: 'Protobuf streaming; generous request budgets.',
    pricingNote: 'Free.',
    markets: 'forex,metals,indices,energies',
  },
  // ---- US stocks ----
  {
    key: 'alpaca',
    name: 'Alpaca Trading API',
    vendor: 'Alpaca Markets',
    docsUrl: 'https://docs.alpaca.markets/',
    baseUrl: 'https://api.alpaca.markets',
    authType: 'api_key_secret',
    authNote: 'API key ID + secret in APCA-API-KEY-ID / APCA-API-SECRET-KEY headers. Paper trading at paper-api.alpaca.markets.',
    exchanges: 'NYSE,NASDAQ',
    capabilities: 'quotes,historical,streaming,orders,portfolio,fractional_shares,crypto',
    rateLimitNote: '200 req/min (basic), higher on paid data plans.',
    pricingNote: 'Commission-free; free API.',
    markets: 'us_stocks,crypto',
  },
  {
    key: 'tradier',
    name: 'Tradier Brokerage API',
    vendor: 'Tradier',
    docsUrl: 'https://documentation.tradier.com/',
    baseUrl: 'https://api.tradier.com/v1',
    authType: 'static_token',
    authNote: 'Bearer access token from the Tradier dashboard; sandbox environment available.',
    exchanges: 'NYSE,NASDAQ,OPRA',
    capabilities: 'quotes,historical,streaming,orders,options,portfolio',
    rateLimitNote: '120 req/min market data, 60 req/min trading.',
    pricingNote: 'Free API with brokerage account.',
    markets: 'us_stocks',
  },
  {
    key: 'schwab',
    name: 'Schwab Trader API',
    vendor: 'Charles Schwab',
    docsUrl: 'https://developer.schwab.com/',
    baseUrl: 'https://api.schwabapi.com',
    authType: 'oauth2',
    authNote: 'OAuth2 app from the Schwab developer portal (successor to the TD Ameritrade API).',
    exchanges: 'NYSE,NASDAQ',
    capabilities: 'quotes,historical,streaming,orders,options,portfolio',
    rateLimitNote: '120 req/min per app.',
    pricingNote: 'Free with a Schwab account.',
    markets: 'us_stocks',
  },
  // ---- Europe stocks ----
  {
    key: 'trading212',
    name: 'Trading 212 API',
    vendor: 'Trading 212',
    docsUrl: 'https://t212public-api-docs.redoc.ly/',
    baseUrl: 'https://live.trading212.com/api/v0',
    authType: 'api_key',
    authNote: 'API key generated in the Trading 212 app settings, passed in the Authorization header.',
    exchanges: 'LSE,Euronext,XETRA,NYSE,NASDAQ',
    capabilities: 'quotes,orders,portfolio,pies',
    rateLimitNote: 'Per-endpoint limits (1–50 req/min).',
    pricingNote: 'Free.',
    markets: 'europe_stocks,us_stocks',
  },
  {
    key: 'xtb',
    name: 'XTB xAPI',
    vendor: 'XTB',
    docsUrl: 'http://developers.xstore.pro/documentation/',
    baseUrl: 'wss://ws.xtb.com/real',
    authType: 'mt_account',
    authNote: 'xStation account number + password over the xAPI websocket; demo endpoint available.',
    exchanges: 'OTC CFDs + EU equities',
    capabilities: 'quotes,historical,streaming,orders,portfolio',
    rateLimitNote: 'Websocket command throttles.',
    pricingNote: 'Free.',
    markets: 'forex,indices,europe_stocks',
  },
  // ---- Asia-Pacific stocks ----
  {
    key: 'tiger_brokers',
    name: 'Tiger OpenAPI',
    vendor: 'Tiger Brokers',
    docsUrl: 'https://quant.itigerup.com/openapi/en/',
    baseUrl: 'https://openapi.tigerfintech.com',
    authType: 'api_key_secret',
    authNote: 'Developer ID + RSA key pair from the Tiger Quant portal.',
    exchanges: 'HKEX,SGX,NYSE,NASDAQ',
    capabilities: 'quotes,historical,orders,portfolio',
    rateLimitNote: 'Per-endpoint QPS limits.',
    pricingNote: 'Free with a Tiger account.',
    markets: 'asia_stocks,us_stocks',
  },
  {
    key: 'moomoo',
    name: 'moomoo OpenAPI',
    vendor: 'moomoo (Futu)',
    docsUrl: 'https://openapi.moomoo.com/futu-api-doc/en/',
    baseUrl: 'opend://localhost:11111',
    authType: 'mt_account',
    authNote: 'Runs through the OpenD gateway with the moomoo account login; covers HK, US and SG markets.',
    exchanges: 'HKEX,NYSE,NASDAQ,SGX',
    capabilities: 'quotes,historical,streaming,orders,portfolio',
    rateLimitNote: 'Gateway-bound quotas by data plan.',
    pricingNote: 'Free API; data plans vary.',
    markets: 'asia_stocks,us_stocks',
  },
  // ---- Crypto exchanges (global) ----
  {
    key: 'binance',
    name: 'Binance Spot API',
    vendor: 'Binance',
    docsUrl: 'https://developers.binance.com/docs/binance-spot-api-docs',
    baseUrl: 'https://api.binance.com',
    authType: 'api_key_secret',
    authNote: 'API key + HMAC secret from Binance account settings; IP allow-listing recommended, withdrawals permission OFF.',
    exchanges: 'Binance spot/futures',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: 'Weight-based: 6,000 request weight/min.',
    pricingNote: 'Free API; trading fees apply.',
    markets: 'crypto',
  },
  {
    key: 'coinbase',
    name: 'Coinbase Advanced Trade API',
    vendor: 'Coinbase',
    docsUrl: 'https://docs.cdp.coinbase.com/advanced-trade/docs/welcome',
    baseUrl: 'https://api.coinbase.com',
    authType: 'api_key_secret',
    authNote: 'CDP API key + EC private key (JWT-signed requests) from the Coinbase Developer Platform.',
    exchanges: 'Coinbase Exchange',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: '~30 req/s private endpoints.',
    pricingNote: 'Free API; trading fees apply.',
    markets: 'crypto',
  },
  {
    key: 'kraken',
    name: 'Kraken REST API',
    vendor: 'Kraken',
    docsUrl: 'https://docs.kraken.com/api/',
    baseUrl: 'https://api.kraken.com',
    authType: 'api_key_secret',
    authNote: 'API key + private key (HMAC-signed nonce) from Kraken security settings.',
    exchanges: 'Kraken spot/futures',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: 'Tier-based counter system.',
    pricingNote: 'Free API; trading fees apply.',
    markets: 'crypto',
  },
  {
    key: 'bybit',
    name: 'Bybit V5 API',
    vendor: 'Bybit',
    docsUrl: 'https://bybit-exchange.github.io/docs/v5/intro',
    baseUrl: 'https://api.bybit.com',
    authType: 'api_key_secret',
    authNote: 'API key + secret (HMAC) from Bybit account; unified V5 API for spot, perp and options.',
    exchanges: 'Bybit spot/derivatives',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: '10–50 req/s by endpoint group.',
    pricingNote: 'Free API; trading fees apply.',
    markets: 'crypto',
  },
  {
    key: 'okx',
    name: 'OKX V5 API',
    vendor: 'OKX',
    docsUrl: 'https://www.okx.com/docs-v5/en/',
    baseUrl: 'https://www.okx.com',
    authType: 'api_key_secret',
    authNote: 'API key + secret + passphrase (put the passphrase in the client-code field).',
    exchanges: 'OKX spot/derivatives',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: 'Per-endpoint, ~20 req/2s typical.',
    pricingNote: 'Free API; trading fees apply.',
    markets: 'crypto',
  },
  {
    key: 'coindcx',
    name: 'CoinDCX API',
    vendor: 'CoinDCX (India)',
    docsUrl: 'https://docs.coindcx.com/',
    baseUrl: 'https://api.coindcx.com',
    authType: 'api_key_secret',
    authNote: 'API key + HMAC secret from CoinDCX settings — India-registered crypto exchange (INR pairs).',
    exchanges: 'CoinDCX',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: 'Per-endpoint throttles.',
    pricingNote: 'Free API; trading fees + TDS rules apply in India.',
    markets: 'crypto,india',
  },
]
