// Global broker & exchange API roster, grouped by the markets each serves.
// Same row shape as the Indian providers (stored in india_api_providers with a
// `markets` tag). Forex/CFD and crypto venues are global; equity brokers are
// tagged to their home market(s). Users only see brokers for the markets they
// selected.

import type { IndiaProviderDef } from './india/providers'

export const GLOBAL_BROKERS: IndiaProviderDef[] = [
  // ---- Forex & CFDs (global) ----
  {
    key: 'mt5_bridge',
    name: 'MetaTrader 5 Bridge',
    vendor: 'Any MT5 broker (IC Markets, Pepperstone, Exness, XM…)',
    docsUrl: 'https://www.mql5.com/en/docs/integration',
    baseUrl: 'mt5://terminal-bridge',
    authType: 'mt_account',
    authNote: 'Connects to any MT5 broker account: account number + password + broker server name. The bridge terminal handles quotes and execution.',
    exchanges: 'OTC — broker dependent',
    capabilities: 'quotes,historical,orders,portfolio,margins,hedging',
    rateLimitNote: 'Terminal-bound; no REST rate limits.',
    pricingNote: 'Free — trade costs are broker spreads/commissions.',
    markets: 'forex,metals,indices,energies,crypto',
  },
  {
    key: 'mt4_bridge',
    name: 'MetaTrader 4 Bridge',
    vendor: 'Any MT4 broker',
    docsUrl: 'https://docs.mql4.com/',
    baseUrl: 'mt4://terminal-bridge',
    authType: 'mt_account',
    authNote: 'Legacy MT4 accounts: account number + password + server name via the bridge terminal.',
    exchanges: 'OTC — broker dependent',
    capabilities: 'quotes,historical,orders,portfolio,margins,hedging',
    rateLimitNote: 'Terminal-bound.',
    pricingNote: 'Free — broker costs apply.',
    markets: 'forex,metals,indices,energies',
  },
  {
    key: 'oanda',
    name: 'OANDA v20 REST API',
    vendor: 'OANDA',
    docsUrl: 'https://developer.oanda.com/rest-live-v20/introduction/',
    baseUrl: 'https://api-fxtrade.oanda.com/v3',
    authType: 'static_token',
    authNote: 'Personal access token from the OANDA account portal, passed as a Bearer token. Practice environment at api-fxpractice.oanda.com.',
    exchanges: 'OTC',
    capabilities: 'quotes,historical,streaming,orders,portfolio,margins',
    rateLimitNote: '120 req/s REST; streaming endpoints for prices.',
    pricingNote: 'Free with an OANDA account.',
    markets: 'forex,metals,indices,energies',
  },
  {
    key: 'ig_markets',
    name: 'IG Trading API',
    vendor: 'IG Group',
    docsUrl: 'https://labs.ig.com/',
    baseUrl: 'https://api.ig.com/gateway/deal',
    authType: 'api_key_secret_daily_token',
    authNote: 'API key + account identifier + password; login returns CST and security tokens used on every request.',
    exchanges: 'OTC / LSE-referenced CFDs',
    capabilities: 'quotes,historical,streaming,orders,portfolio,margins',
    rateLimitNote: '30 non-trading req/min, 100 trading req/min (per app).',
    pricingNote: 'Free with an IG account.',
    markets: 'forex,indices,metals,energies,europe_stocks',
  },
  {
    key: 'saxo',
    name: 'Saxo OpenAPI',
    vendor: 'Saxo Bank',
    docsUrl: 'https://www.developer.saxo/openapi/learn',
    baseUrl: 'https://gateway.saxobank.com/openapi',
    authType: 'oauth2',
    authNote: 'OAuth2 app from the Saxo developer portal; access tokens are refreshed via the standard flow.',
    exchanges: 'Global multi-asset',
    capabilities: 'quotes,historical,streaming,orders,portfolio,margins',
    rateLimitNote: 'Per-app throttle policies by endpoint group.',
    pricingNote: 'Free with a Saxo account.',
    markets: 'forex,indices,europe_stocks,us_stocks',
  },
  {
    key: 'interactive_brokers',
    name: 'IBKR Web API',
    vendor: 'Interactive Brokers',
    docsUrl: 'https://www.interactivebrokers.com/campus/ibkr-api-page/web-api/',
    baseUrl: 'https://api.ibkr.com/v1/api',
    authType: 'oauth2',
    authNote: 'OAuth (or the Client Portal Gateway) authenticates the IBKR session. One account covers 150+ markets worldwide.',
    exchanges: 'NYSE,NASDAQ,LSE,XETRA,TSE,HKEX,ASX + forex',
    capabilities: 'quotes,historical,streaming,orders,portfolio,margins',
    rateLimitNote: '~10 req/s general; endpoint-specific throttles.',
    pricingNote: 'Free API; market-data subscriptions per exchange.',
    markets: 'us_stocks,europe_stocks,asia_stocks,forex,indices',
  },
  {
    key: 'ctrader',
    name: 'cTrader Open API',
    vendor: 'Spotware (FxPro, IC Markets cTrader, Pepperstone…)',
    docsUrl: 'https://help.ctrader.com/open-api/',
    baseUrl: 'https://openapi.ctrader.com',
    authType: 'oauth2',
    authNote: 'OAuth2 app from the cTrader developer portal; works with any broker running cTrader.',
    exchanges: 'OTC — broker dependent',
    capabilities: 'quotes,historical,streaming,orders,portfolio,margins',
    rateLimitNote: 'Protobuf streaming; generous request budgets.',
    pricingNote: 'Free.',
    markets: 'forex,metals,indices,energies',
  },
  // ---- US stocks ----
  {
    key: 'alpaca',
    name: 'Alpaca Trading API',
    vendor: 'Alpaca Markets',
    docsUrl: 'https://docs.alpaca.markets/',
    baseUrl: 'https://api.alpaca.markets',
    authType: 'api_key_secret',
    authNote: 'API key ID + secret in APCA-API-KEY-ID / APCA-API-SECRET-KEY headers. Paper trading at paper-api.alpaca.markets.',
    exchanges: 'NYSE,NASDAQ',
    capabilities: 'quotes,historical,streaming,orders,portfolio,fractional_shares,crypto',
    rateLimitNote: '200 req/min (basic), higher on paid data plans.',
    pricingNote: 'Commission-free; free API.',
    markets: 'us_stocks,crypto',
  },
  {
    key: 'tradier',
    name: 'Tradier Brokerage API',
    vendor: 'Tradier',
    docsUrl: 'https://documentation.tradier.com/',
    baseUrl: 'https://api.tradier.com/v1',
    authType: 'static_token',
    authNote: 'Bearer access token from the Tradier dashboard; sandbox environment available.',
    exchanges: 'NYSE,NASDAQ,OPRA',
    capabilities: 'quotes,historical,streaming,orders,options,portfolio',
    rateLimitNote: '120 req/min market data, 60 req/min trading.',
    pricingNote: 'Free API with brokerage account.',
    markets: 'us_stocks',
  },
  {
    key: 'schwab',
    name: 'Schwab Trader API',
    vendor: 'Charles Schwab',
    docsUrl: 'https://developer.schwab.com/',
    baseUrl: 'https://api.schwabapi.com',
    authType: 'oauth2',
    authNote: 'OAuth2 app from the Schwab developer portal (successor to the TD Ameritrade API).',
    exchanges: 'NYSE,NASDAQ',
    capabilities: 'quotes,historical,streaming,orders,options,portfolio',
    rateLimitNote: '120 req/min per app.',
    pricingNote: 'Free with a Schwab account.',
    markets: 'us_stocks',
  },
  // ---- Europe stocks ----
  {
    key: 'trading212',
    name: 'Trading 212 API',
    vendor: 'Trading 212',
    docsUrl: 'https://t212public-api-docs.redoc.ly/',
    baseUrl: 'https://live.trading212.com/api/v0',
    authType: 'api_key',
    authNote: 'API key generated in the Trading 212 app settings, passed in the Authorization header.',
    exchanges: 'LSE,Euronext,XETRA,NYSE,NASDAQ',
    capabilities: 'quotes,orders,portfolio,pies',
    rateLimitNote: 'Per-endpoint limits (1–50 req/min).',
    pricingNote: 'Free.',
    markets: 'europe_stocks,us_stocks',
  },
  {
    key: 'xtb',
    name: 'XTB xAPI',
    vendor: 'XTB',
    docsUrl: 'https://peterszombati.github.io/xapi-node/',
    baseUrl: 'wss://ws.xtb.com/real',
    authType: 'mt_account',
    authNote: 'xStation account number + password over the xAPI websocket; demo endpoint available.',
    exchanges: 'OTC CFDs + EU equities',
    capabilities: 'quotes,historical,streaming,orders,portfolio',
    rateLimitNote: 'Websocket command throttles.',
    pricingNote: 'Free.',
    markets: 'forex,indices,europe_stocks',
  },
  // ---- Asia-Pacific stocks ----
  {
    key: 'tiger_brokers',
    name: 'Tiger OpenAPI',
    vendor: 'Tiger Brokers',
    docsUrl: 'https://quant.itigerup.com/openapi/en/',
    baseUrl: 'https://openapi.tigerfintech.com',
    authType: 'api_key_secret',
    authNote: 'Developer ID + RSA key pair from the Tiger Quant portal.',
    exchanges: 'HKEX,SGX,NYSE,NASDAQ',
    capabilities: 'quotes,historical,orders,portfolio',
    rateLimitNote: 'Per-endpoint QPS limits.',
    pricingNote: 'Free with a Tiger account.',
    markets: 'asia_stocks,us_stocks',
  },
  {
    key: 'moomoo',
    name: 'moomoo OpenAPI',
    vendor: 'moomoo (Futu)',
    docsUrl: 'https://openapi.moomoo.com/moomoo-api-doc/en/',
    baseUrl: 'opend://localhost:11111',
    authType: 'mt_account',
    authNote: 'Runs through the OpenD gateway with the moomoo account login; covers HK, US and SG markets.',
    exchanges: 'HKEX,NYSE,NASDAQ,SGX',
    capabilities: 'quotes,historical,streaming,orders,portfolio',
    rateLimitNote: 'Gateway-bound quotas by data plan.',
    pricingNote: 'Free API; data plans vary.',
    markets: 'asia_stocks,us_stocks',
  },
  // ---- Crypto exchanges (global) ----
  {
    key: 'binance',
    name: 'Binance Spot API',
    vendor: 'Binance',
    docsUrl: 'https://developers.binance.com/docs/binance-spot-api-docs',
    baseUrl: 'https://api.binance.com',
    authType: 'api_key_secret',
    authNote: 'API key + HMAC secret from Binance account settings; IP allow-listing recommended, withdrawals permission OFF.',
    exchanges: 'Binance spot/futures',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: 'Weight-based: 6,000 request weight/min.',
    pricingNote: 'Free API; trading fees apply.',
    markets: 'crypto',
  },
  {
    key: 'coinbase',
    name: 'Coinbase Advanced Trade API',
    vendor: 'Coinbase',
    docsUrl: 'https://docs.cdp.coinbase.com/advanced-trade/docs/welcome',
    baseUrl: 'https://api.coinbase.com',
    authType: 'api_key_secret',
    authNote: 'CDP API key + EC private key (JWT-signed requests) from the Coinbase Developer Platform.',
    exchanges: 'Coinbase Exchange',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: '~30 req/s private endpoints.',
    pricingNote: 'Free API; trading fees apply.',
    markets: 'crypto',
  },
  {
    key: 'kraken',
    name: 'Kraken REST API',
    vendor: 'Kraken',
    docsUrl: 'https://docs.kraken.com/api/',
    baseUrl: 'https://api.kraken.com',
    authType: 'api_key_secret',
    authNote: 'API key + private key (HMAC-signed nonce) from Kraken security settings.',
    exchanges: 'Kraken spot/futures',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: 'Tier-based counter system.',
    pricingNote: 'Free API; trading fees apply.',
    markets: 'crypto',
  },
  {
    key: 'bybit',
    name: 'Bybit V5 API',
    vendor: 'Bybit',
    docsUrl: 'https://bybit-exchange.github.io/docs/v5/intro',
    baseUrl: 'https://api.bybit.com',
    authType: 'api_key_secret',
    authNote: 'API key + secret (HMAC) from Bybit account; unified V5 API for spot, perp and options.',
    exchanges: 'Bybit spot/derivatives',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: '10–50 req/s by endpoint group.',
    pricingNote: 'Free API; trading fees apply.',
    markets: 'crypto',
  },
  {
    key: 'okx',
    name: 'OKX V5 API',
    vendor: 'OKX',
    docsUrl: 'https://app.okx.com/docs-v5/en/',
    baseUrl: 'https://www.okx.com',
    authType: 'api_key_secret',
    authNote: 'API key + secret + passphrase (put the passphrase in the client-code field).',
    exchanges: 'OKX spot/derivatives',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: 'Per-endpoint, ~20 req/2s typical.',
    pricingNote: 'Free API; trading fees apply.',
    markets: 'crypto',
  },
  {
    key: 'coindcx',
    name: 'CoinDCX API',
    vendor: 'CoinDCX (India)',
    docsUrl: 'https://docs.coindcx.com/',
    baseUrl: 'https://api.coindcx.com',
    authType: 'api_key_secret',
    authNote: 'API key + HMAC secret from CoinDCX settings — India-registered crypto exchange (INR pairs).',
    exchanges: 'CoinDCX',
    capabilities: 'quotes,historical,websocket,orders,portfolio',
    rateLimitNote: 'Per-endpoint throttles.',
    pricingNote: 'Free API; trading fees + TDS rules apply in India.',
    markets: 'crypto,india',
  },

  // ---- Forex & CFDs — additional global venues ----
  { key: 'fxcm', name: 'FXCM REST API', vendor: 'FXCM', docsUrl: 'https://fxcm-api.readthedocs.io/', baseUrl: 'https://api.fxcm.com', authType: 'static_token', authNote: 'Persistent access token from the FXCM trading station; REST + socket.io streaming.', exchanges: 'OTC', capabilities: 'quotes,historical,orders,portfolio,margins', rateLimitNote: 'Per-endpoint throttles.', pricingNote: 'Free for FXCM accounts.', markets: 'forex' },
  { key: 'dukascopy', name: 'Dukascopy JForex API', vendor: 'Dukascopy Bank', docsUrl: 'https://www.dukascopy.com/wiki/en/development', baseUrl: 'https://www.dukascopy.com', authType: 'api_key_secret', authNote: 'JForex/FIX APIs for Dukascopy accounts; historical tick data also public.', exchanges: 'OTC / SWFX', capabilities: 'quotes,historical,orders,portfolio,fix', rateLimitNote: 'Per-plan.', pricingNote: 'Free for account holders.', markets: 'forex' },
  { key: 'deriv', name: 'Deriv API', vendor: 'Deriv', docsUrl: 'https://api.deriv.com/', baseUrl: 'wss://ws.derivws.com', authType: 'static_token', authNote: 'API token from the Deriv dashboard; websocket JSON API for quotes and trading.', exchanges: 'OTC / synthetic indices', capabilities: 'quotes,historical,websocket,orders,portfolio', rateLimitNote: 'Per-connection limits.', pricingNote: 'Free.', markets: 'forex' },
  { key: 'exante', name: 'EXANTE HTTP API', vendor: 'EXANTE', docsUrl: 'https://api-live.exante.eu/api-docs/', baseUrl: 'https://api-live.exante.eu', authType: 'api_key_secret', authNote: 'Application ID + shared key (JWT/basic); multi-asset institutional-grade broker API.', exchanges: 'Global multi-asset', capabilities: 'quotes,historical,orders,portfolio,margins', rateLimitNote: 'Per-plan.', pricingNote: 'Free for clients.', markets: 'forex,us_stocks,europe_stocks' },
  { key: 'darwinex', name: 'Darwinex API', vendor: 'Darwinex', docsUrl: 'https://www.darwinex.com/algorithmic-trading/darwinex-api', baseUrl: 'https://api.darwinex.com', authType: 'oauth2', authNote: 'OAuth2 tokens from the Darwinex portal; investor + trading APIs.', exchanges: 'OTC', capabilities: 'quotes,historical,orders,portfolio', rateLimitNote: 'Per-endpoint.', pricingNote: 'Free for clients.', markets: 'forex' },
  { key: 'pepperstone', name: 'Pepperstone (via cTrader/MT)', vendor: 'Pepperstone', docsUrl: 'https://pepperstone.com/', baseUrl: 'https://pepperstone.com', authType: 'static_token', authNote: 'No direct public REST API — connect today through the cTrader Open API or MT4/MT5 bridges. Direct-API partnership outreach target.', exchanges: 'OTC', capabilities: 'via_ctrader,via_mt,outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'forex' },
  { key: 'exness', name: 'Exness (via MT)', vendor: 'Exness', docsUrl: 'https://www.exness.com/', baseUrl: 'https://www.exness.com', authType: 'static_token', authNote: 'No public retail REST API — connect today through the MT4/MT5 bridges. Direct-API partnership outreach target.', exchanges: 'OTC', capabilities: 'via_mt,outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'forex' },
  { key: 'plus500', name: 'Plus500', vendor: 'Plus500', docsUrl: 'https://www.plus500.com/', baseUrl: 'https://www.plus500.com', authType: 'static_token', authNote: 'No public API today — EMIL partnership outreach target for CFD connectivity.', exchanges: 'OTC CFDs', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'forex' },

  // ---- United States ----
  { key: 'etrade', name: 'E*TRADE API', vendor: 'E*TRADE (Morgan Stanley)', docsUrl: 'https://developer.etrade.com/home', baseUrl: 'https://api.etrade.com', authType: 'api_key_secret_daily_token', authNote: 'OAuth 1.0a consumer key + secret from the developer portal; session tokens renew daily.', exchanges: 'NYSE,NASDAQ', capabilities: 'quotes,orders,portfolio,options', rateLimitNote: 'Per-endpoint throttles.', pricingNote: 'Free for clients.', markets: 'us_stocks' },
  { key: 'tradestation', name: 'TradeStation API', vendor: 'TradeStation', docsUrl: 'https://api.tradestation.com/docs/', baseUrl: 'https://api.tradestation.com/v3', authType: 'oauth2', authNote: 'OAuth2 from the developer portal; market data + brokerage endpoints.', exchanges: 'NYSE,NASDAQ,futures', capabilities: 'quotes,historical,orders,portfolio,futures,options', rateLimitNote: 'Per-plan.', pricingNote: 'Free for clients.', markets: 'us_stocks' },
  { key: 'tastytrade', name: 'tastytrade Open API', vendor: 'tastytrade', docsUrl: 'https://developer.tastytrade.com/', baseUrl: 'https://api.tastyworks.com', authType: 'api_key_secret_daily_token', authNote: 'Session token via login; certification + production environments.', exchanges: 'NYSE,NASDAQ,options,futures', capabilities: 'quotes,orders,portfolio,options,futures', rateLimitNote: 'Per-endpoint.', pricingNote: 'Free for clients.', markets: 'us_stocks' },
  { key: 'webull', name: 'Webull OpenAPI', vendor: 'Webull', docsUrl: 'https://developer.webull.com/', baseUrl: 'https://api.webull.com', authType: 'api_key_secret', authNote: 'App key + secret from the OpenAPI portal (region-dependent availability).', exchanges: 'NYSE,NASDAQ', capabilities: 'quotes,orders,portfolio', rateLimitNote: 'Per-plan.', pricingNote: 'Free for clients.', markets: 'us_stocks' },
  { key: 'robinhood', name: 'Robinhood', vendor: 'Robinhood', docsUrl: 'https://robinhood.com/', baseUrl: 'https://robinhood.com', authType: 'static_token', authNote: 'No public retail trading API today — EMIL partnership outreach target.', exchanges: 'NYSE,NASDAQ,crypto', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'us_stocks' },
  { key: 'fidelity', name: 'Fidelity', vendor: 'Fidelity Investments', docsUrl: 'https://www.fidelity.com/', baseUrl: 'https://www.fidelity.com', authType: 'static_token', authNote: 'No public retail API (institutional Wealthscape only) — EMIL partnership outreach target.', exchanges: 'NYSE,NASDAQ', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'us_stocks' },

  // ---- United Kingdom ----
  { key: 'capital_com', name: 'Capital.com API', vendor: 'Capital.com', docsUrl: 'https://open-api.capital.com/', baseUrl: 'https://api-capital.backend-capital.com', authType: 'api_key_secret_daily_token', authNote: 'API key from the platform; session created with identifier + password, tokens on every call.', exchanges: 'OTC CFDs / LSE-referenced', capabilities: 'quotes,orders,portfolio,websocket', rateLimitNote: '10 req/s general.', pricingNote: 'Free.', markets: 'uk_stocks,forex' },
  { key: 'cmc_markets', name: 'CMC Markets Connect', vendor: 'CMC Markets', docsUrl: 'https://www.cmcmarkets.com/en-gb/institutional', baseUrl: 'https://www.cmcmarkets.com', authType: 'api_key_secret', authNote: 'Institutional Connect API (REST/FIX); retail API access is an EMIL partnership outreach target.', exchanges: 'OTC CFDs', capabilities: 'institutional_api,fix,outreach_target', rateLimitNote: '-', pricingNote: 'Institutional terms.', markets: 'uk_stocks,forex' },
  { key: 'hargreaves_lansdown', name: 'Hargreaves Lansdown', vendor: 'Hargreaves Lansdown', docsUrl: 'https://www.hl.co.uk/', baseUrl: 'https://www.hl.co.uk', authType: 'static_token', authNote: 'No public API today — EMIL partnership outreach target (largest UK retail platform).', exchanges: 'LSE', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'uk_stocks' },
  { key: 'freetrade', name: 'Freetrade', vendor: 'Freetrade', docsUrl: 'https://freetrade.io/', baseUrl: 'https://freetrade.io', authType: 'static_token', authNote: 'No public API today — EMIL partnership outreach target.', exchanges: 'LSE,NYSE,NASDAQ', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'uk_stocks' },

  // ---- Europe ----
  { key: 'etoro', name: 'eToro API', vendor: 'eToro', docsUrl: 'https://api-portal.etoro.com/', baseUrl: 'https://api.etoro.com', authType: 'api_key', authNote: 'API key from the eToro developer portal (public API program).', exchanges: 'Multi-asset', capabilities: 'quotes,portfolio,orders', rateLimitNote: 'Per-plan.', pricingNote: 'Free tier.', markets: 'europe_stocks,forex' },
  { key: 'swissquote', name: 'Swissquote API', vendor: 'Swissquote Bank', docsUrl: 'https://developer.swissquote.com/', baseUrl: 'https://api.swissquote.com', authType: 'oauth2', authNote: 'OAuth2 apps via the Swissquote developer portal; banking + trading endpoints.', exchanges: 'SIX,global', capabilities: 'quotes,orders,portfolio', rateLimitNote: 'Per-plan.', pricingNote: 'Free for clients.', markets: 'europe_stocks,forex' },
  { key: 'degiro', name: 'DEGIRO', vendor: 'DEGIRO (flatexDEGIRO)', docsUrl: 'https://www.degiro.com/', baseUrl: 'https://trader.degiro.nl', authType: 'static_token', authNote: 'No official public API — EMIL partnership outreach target (large EU retail broker).', exchanges: 'Euronext,XETRA,LSE', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'europe_stocks' },
  { key: 'trade_republic', name: 'Trade Republic', vendor: 'Trade Republic', docsUrl: 'https://traderepublic.com/', baseUrl: 'https://traderepublic.com', authType: 'static_token', authNote: 'No public API today — EMIL partnership outreach target.', exchanges: 'LS Exchange,XETRA', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'europe_stocks' },

  // ---- Asia-Pacific ----
  { key: 'kabucom', name: 'kabu STATION API', vendor: 'au Kabucom Securities (Japan)', docsUrl: 'https://kabucom.github.io/kabusapi/ptal/', baseUrl: 'http://localhost:18080/kabusapi', authType: 'api_key', authNote: 'Local kabu STATION app exposes the REST API with an API password (Japan residents).', exchanges: 'TSE', capabilities: 'quotes,orders,portfolio', rateLimitNote: 'Local app limits.', pricingNote: 'Free for clients.', markets: 'asia_stocks' },
  { key: 'rakuten_sec', name: 'Rakuten Securities', vendor: 'Rakuten Securities (Japan)', docsUrl: 'https://www.rakuten-sec.co.jp/', baseUrl: 'https://www.rakuten-sec.co.jp', authType: 'static_token', authNote: 'MarketSpeed terminals only; no open REST API — EMIL partnership outreach target.', exchanges: 'TSE', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'asia_stocks' },
  { key: 'monex_jp', name: 'Monex Securities', vendor: 'Monex Group (Japan)', docsUrl: 'https://www.monex.co.jp/', baseUrl: 'https://www.monex.co.jp', authType: 'static_token', authNote: 'No open retail API — EMIL partnership outreach target.', exchanges: 'TSE', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'asia_stocks' },
  { key: 'longbridge', name: 'Longbridge OpenAPI', vendor: 'Longbridge (HK/SG)', docsUrl: 'https://open.longbridgeapp.com/en/', baseUrl: 'https://openapi.longbridgeapp.com', authType: 'api_key_secret_daily_token', authNote: 'App key + secret + access token from the OpenAPI console; SDKs for quotes and trading.', exchanges: 'HKEX,NYSE,NASDAQ,SGX', capabilities: 'quotes,historical,websocket,orders,portfolio', rateLimitNote: 'Per-plan.', pricingNote: 'Free for clients.', markets: 'asia_stocks' },
  { key: 'phillip_poems', name: 'POEMS (PhillipCapital)', vendor: 'PhillipCapital (Singapore)', docsUrl: 'https://www.poems.com.sg/', baseUrl: 'https://www.poems.com.sg', authType: 'static_token', authNote: 'No open retail API — EMIL partnership outreach target.', exchanges: 'SGX', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'asia_stocks' },
  { key: 'stake_au', name: 'Stake', vendor: 'Stake (Australia)', docsUrl: 'https://hellostake.com/', baseUrl: 'https://hellostake.com', authType: 'static_token', authNote: 'No public API today — EMIL partnership outreach target.', exchanges: 'ASX,NYSE,NASDAQ', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'asia_stocks' },
  { key: 'commsec', name: 'CommSec', vendor: 'Commonwealth Bank (Australia)', docsUrl: 'https://www.commsec.com.au/', baseUrl: 'https://www.commsec.com.au', authType: 'static_token', authNote: 'No public API today — EMIL partnership outreach target (largest AU retail broker).', exchanges: 'ASX', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'asia_stocks' },

  // ---- Canada ----
  { key: 'questrade', name: 'Questrade API', vendor: 'Questrade', docsUrl: 'https://www.questrade.com/api', baseUrl: 'https://api01.iq.questrade.com', authType: 'oauth2', authNote: 'OAuth2 refresh-token flow from the API centre; market data + account endpoints.', exchanges: 'TSX,NYSE,NASDAQ', capabilities: 'quotes,orders,portfolio', rateLimitNote: '30 req/s data and account.', pricingNote: 'Free for clients.', markets: 'canada_stocks' },
  { key: 'wealthsimple', name: 'Wealthsimple', vendor: 'Wealthsimple', docsUrl: 'https://www.wealthsimple.com/', baseUrl: 'https://www.wealthsimple.com', authType: 'static_token', authNote: 'No public trading API — EMIL partnership outreach target.', exchanges: 'TSX,US', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'canada_stocks' },

  // ---- Middle East ----
  { key: 'sarwa', name: 'Sarwa Trade', vendor: 'Sarwa (UAE)', docsUrl: 'https://www.sarwa.co/', baseUrl: 'https://www.sarwa.co', authType: 'static_token', authNote: 'No public API today — EMIL partnership outreach target (UAE digital broker).', exchanges: 'US via UAE', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'mena_stocks' },
  { key: 'efg_hermes', name: 'EFG Hermes ONE', vendor: 'EFG Holding (MENA)', docsUrl: 'https://www.efghermesone.com/', baseUrl: 'https://www.efghermesone.com', authType: 'static_token', authNote: 'Regional platform across MENA exchanges; API access is an EMIL partnership outreach target.', exchanges: 'EGX,ADX,DFM,Tadawul', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'mena_stocks' },
  { key: 'derayah', name: 'Derayah Financial', vendor: 'Derayah (Saudi Arabia)', docsUrl: 'https://www.derayah.com/', baseUrl: 'https://www.derayah.com', authType: 'static_token', authNote: 'No public API today — EMIL partnership outreach target (Tadawul access).', exchanges: 'Tadawul', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'mena_stocks' },

  // ---- Africa ----
  { key: 'easyequities', name: 'EasyEquities', vendor: 'Purple Group (South Africa)', docsUrl: 'https://www.easyequities.co.za/', baseUrl: 'https://www.easyequities.co.za', authType: 'static_token', authNote: 'Partner integrations exist; open API access is an EMIL partnership outreach target.', exchanges: 'JSE,US', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'africa_stocks' },
  { key: 'bamboo_ng', name: 'Bamboo', vendor: 'Bamboo (Nigeria)', docsUrl: 'https://investbamboo.com/', baseUrl: 'https://investbamboo.com', authType: 'static_token', authNote: 'No public API today — EMIL partnership outreach target.', exchanges: 'NGX,US', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'africa_stocks' },
  { key: 'chaka_ng', name: 'Chaka', vendor: 'Chaka (Nigeria)', docsUrl: 'https://chaka.com/', baseUrl: 'https://chaka.com', authType: 'static_token', authNote: 'Embedded-finance APIs for partners; retail API access is an EMIL partnership outreach target.', exchanges: 'NGX,US', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'africa_stocks' },

  // ---- Latin America ----
  { key: 'xp_inc', name: 'XP Investimentos', vendor: 'XP Inc. (Brazil)', docsUrl: 'https://www.xpi.com.br/', baseUrl: 'https://www.xpi.com.br', authType: 'static_token', authNote: 'No open retail API — EMIL partnership outreach target (largest BR retail broker).', exchanges: 'B3', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'latam_stocks' },
  { key: 'nuinvest', name: 'NuInvest', vendor: 'Nubank (Brazil)', docsUrl: 'https://www.nuinvest.com.br/', baseUrl: 'https://www.nuinvest.com.br', authType: 'static_token', authNote: 'No public API today — EMIL partnership outreach target.', exchanges: 'B3', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'latam_stocks' },
  { key: 'gbm_mx', name: 'GBM+', vendor: 'GBM (Mexico)', docsUrl: 'https://gbm.com/', baseUrl: 'https://gbm.com', authType: 'static_token', authNote: 'No public retail API — EMIL partnership outreach target (BMV access).', exchanges: 'BMV,BIVA', capabilities: 'outreach_target', rateLimitNote: '-', pricingNote: '-', markets: 'latam_stocks' },
]
