'use client'

import { Panel } from '@/components/cockpit/panel'
import { Lightbulb } from 'lucide-react'

const STATUS_TONE: Record<string, string> = {
  proposed: 'text-slate-300 border-slate-500/40 bg-slate-500/10',
  researching: 'text-cyan-300 border-cyan-500/40 bg-cyan-500/10',
  testing: 'text-violet-300 border-violet-500/40 bg-violet-500/10',
  supported: 'text-emerald-300 border-emerald-500/40 bg-emerald-500/10',
  weak: 'text-amber-300 border-amber-500/40 bg-amber-500/10',
  rejected: 'text-red-300 border-red-500/40 bg-red-500/10',
  regime_dependent: 'text-violet-300 border-violet-500/40 bg-violet-500/10',
}

const ORIGIN_LABEL: Record<string, string> = {
  source_claim: 'From a source claim',
  emil_generated: 'EMIL-GENERATED HYPOTHESIS',
  contradiction_probe: 'Contradiction probe',
  admin: 'Admin-created',
}

export default function HypothesesTab({ overview }: { overview: any }) {
  const hypotheses = overview?.hypotheses ?? []
  return (
    <Panel title={`Research Hypotheses (${hypotheses.length}) — learning does not mean accepting`} icon={Lightbulb} accent="violet">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {hypotheses.map((h: any) => (
          <div key={h.id} className="rounded-md border border-border bg-background/40 p-3">
            <div className="flex items-start justify-between gap-2">
              <p className="text-xs font-semibold text-slate-200">{h.title}</p>
              <span className={`shrink-0 text-[9px] uppercase font-bold px-1.5 py-0.5 rounded border ${STATUS_TONE[h.status] ?? STATUS_TONE.proposed}`}>{h.status.replace('_', ' ')}</span>
            </div>
            <p className={`text-[10px] mt-0.5 ${h.originType === 'emil_generated' ? 'text-amber-300 font-semibold' : 'text-slate-500'}`}>{ORIGIN_LABEL[h.originType] ?? h.originType}</p>
            <p className="text-[11px] text-slate-400 mt-1.5">{h.statement}</p>
            {h.testPlan ? <p className="text-[10px] text-cyan-300/80 mt-1.5"><span className="text-slate-500">Test plan:</span> {h.testPlan}</p> : null}
            {h.findings ? <p className="text-[10px] text-emerald-300/80 mt-1"><span className="text-slate-500">Findings:</span> {h.findings}</p> : null}
            <div className="mt-2 flex items-center gap-2">
              <div className="flex-1 h-1.5 rounded bg-slate-800 overflow-hidden">
                <div className={`h-full rounded ${h.confidence >= 65 ? 'bg-emerald-500' : h.confidence >= 40 ? 'bg-amber-500' : 'bg-slate-500'}`} style={{ width: `${h.confidence}%` }} />
              </div>
              <span className="num text-[10px] text-slate-400">{Math.round(h.confidence)}/100</span>
            </div>
          </div>
        ))}
        {hypotheses.length === 0 ? <p className="text-xs text-slate-500 col-span-2 text-center py-6">No hypotheses yet — they are created automatically as EMIL studies sources, or generated by EMIL in the Strategy Lab.</p> : null}
      </div>
    </Panel>
  )
}
